services:
  tautulli:
    # Build from your local Dockerfile instead of pulling from Docker Hub
    build:
      context: ../..  # Project root
      dockerfile: docker/custom-tautulli/Dockerfile
    # The final name/tag for the built image
    image: tautulli_recommendations:latest
    network_mode: "host"
    container_name: tautulli_recommendations
    # Map Tautulli's default port 8181 to the host
    ports:
      - "8181:8181"

    # Volumes for Tautulli config, your scripts, etc.
    volumes:
      - /absolute/host/path/to/config/Tautalli:/config
      - /absolute/host/path/to/movies:/Movies


    # If you have environment variables, set them here:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York

    # Recommended so it restarts automatically
    restart: unless-stopped

